server-web:
  image: nginx
  ports: 
    - "80:80"
  volumes:
    - ./src:/var/www
    - ./config/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
php:
  image: nmcteam/php56
  volumes:
    - ./config/php/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./src:/var/www
  links:
    - db-mysql
db-mysql:
  image: sameersbn/mysql
  volumes:
    - /var/lib/mysql
  environment:
    - DB_NAME=demo
    - DB_USER=root
    - DB_PASS=1234
