server-web:
  image: nginx
  ports: 
    - "80:80"
  volumes:
    - ./src:/var/www
    - ./config/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    - ./src/storage/logs/laravel.log:/var/www/storage/logs/laravel.log
  links:
    - php
php:
  image: nmcteam/php56
  volumes:
    - ./config/php/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./src:/var/www
    - ./src/storage/logs/laravel.log:/var/www/storage/logs/laravel.log
    - ./log/php:/var/logs
  links:
    - db
db:
  image: sameersbn/mysql
  volumes:
    - /var/lib/mysql
  environment:
    - DB_NAME=demo
    - DB_USER=root
    - DB_PASS=1234
